YAHOO.env.classMap = {"Console": "console", "DOMEventFacade": "event", "Plugin.DragConstrained": "dd", "YUI": "yui", "DataSource.Local": "datasource", "NodeList": "node", "Widget": "widget", "DataSource.Function": "datasource", "Object": "yui", "YUI~array~extras": "collection", "Base": "base", "History.Module": "history", "Plugin.Base": "plugin", "Do.AlterArgs": "event-custom", "Pollable": "datasource", "ClassNameManager": "classnamemanager", "Assert.ObjectAssert": "test", "Plugin.DDWindowScroll": "dd", "plugin.NodeFocusManager": "node-focusmanager", "Assert.ComparisonFailure": "test", "DataSchema.XML": "dataschema", "YUI~dump": "dump", "Loader": "yui", "WidgetPosition": "widget-position", "Event": "event", "State": "attribute", "CustomEvent": "event-custom", "Plugin.Drop": "dd", "DataSource.Get": "datasource", "Selector": "dom", "DataSourceXMLSchema": "datasource", "DD.Drop": "dd", "DataType.Number": "datatype", "DataSourceArraySchema": "datasource", "Profiler": "profiler", "Queue": "queue", "DataSource.IO": "datasource", "ImgLoadGroup": "imageloader", "Test.Wait": "test", "Do.Method": "event-custom", "EventTarget": "event-custom", "Get": "yui", "Do.AlterReturn": "event-custom", "Do.Prevent": "event-custom", "Plugin.NodeFX": "anim", "UA": "yui", "DataSourceJSONSchema": "datasource", "Test.TestNode": "test", "DOM": "dom", "Cache": "cache", "ImgLoadImgObj": "imageloader", "plugin.NodeMenuNav": "node-menunav", "DataSchema.Base": "dataschema", "Do.Halt": "event-custom", "Node": "node", "Test.Runner": "test", "Assert.ShouldError": "test", "WidgetPositionExt": "widget-position-ext", "JSON": "json", "Test.Manager": "test", "Cookie": "cookie", "DataType.Date": "datatype", "DataSchema.Array": "dataschema", "Lang": "yui", "DD.Drag": "dd", "DataSchema.JSON": "dataschema", "AsyncQueue": "queue", "Easing": "anim", "Plugin.Drag": "dd", "History": "history", "Plugin.Host": "base", "Plugin.DDNodeScroll": "dd", "Attribute": "attribute", "StyleSheet": "stylesheet", "YUI~oop": "oop", "Assert.Error": "test", "DD.Scroll": "dd", "Overlay": "overlay", "Test.DateAssert": "test", "Subscriber": "event-custom", "Test.ArrayAssert": "test", "YUI~substitute": "substitute", "io": "io", "Test.Suite": "test", "Assert.UnexpectedError": "test", "Do": "event-custom", "Anim": "anim", "Plugin.DDProxy": "dd", "DD.DDM": "dd", "WidgetStack": "widget-stack", "Test.Case": "test", "Assert": "test", "Slider": "slider", "Assert.UnexpectedValue": "test", "config": "yui", "Assert.ShouldFail": "test", "DataSchema.Text": "dataschema", "DataSourceCache": "datasource", "DataType.XML": "datatype", "Test.Reporter": "test", "WidgetStdMod": "widget-stdmod", "Array": "yui", "EventHandle": "event-custom", "Do.Error": "event-custom", "Plugin.ConsoleFilters": "console-filters", "Test.Format.Mock": "test", "DataType.Date.Locale": "datatype", "EventFacade": "event-custom", "DataSourceTextSchema": "datasource"};

YAHOO.env.resolveClass = function(className) {
    var a=className.split('.'), ns=YAHOO.env.classMap;

    for (var i=0; i<a.length; i=i+1) {
        if (ns[a[i]]) {
            ns = ns[a[i]];
        } else {
            return null;
        }
    }

    return ns;
};
