from cm.tests.test_notifications import *
#from cm.tests.test_converters import *
from cm.tests.test_spannifier import *
from cm.tests.test_comment_positioning import *
from cm.tests.test_structure import *
from cm.tests.test_history import *
from cm.tests.test_security import *
from cm.tests.test_activity import *
from cm.tests.test_registration import *
from cm.tests.test_api import *
